import { YouTubeAdapter } from '../platforms/youtube/YoutubeAdapter.ts';
import { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import SubtitleOverlay from './SubtitleOverlay';
import { SubtitleEngine } from '../core/engine/SubtitleEngine';
import { getSettings, addWordHistoryEntry } from '../shared/storage';
import type { CaptionStyle, OverlayLayout } from '../shared/storage';
import { DEFAULT_CAPTION_STYLE, DEFAULT_FONT_SIZE, DEFAULT_OVERLAY_LAYOUT, GOOGLE_FONTS_URL, setSettings } from '../shared/storage';

const adapter = new YouTubeAdapter();
const CAPTURE_TIMEOUT_MS = 8000;

type LiveTrack = { languageCode: string; isAutoGenerated: boolean };

let nativeCaptionStyleEl: HTMLStyleElement | null = null;
function setNativeCaptionsHidden(hidden: boolean) {
  if (!nativeCaptionStyleEl) return;
  nativeCaptionStyleEl.textContent = hidden
    ? '.ytp-caption-window-container { display: none !important; }'
    : '';
}

const requestTranslation = (word: string, sourceLang: string, targetLang: string): Promise<string | null> => {
  return new Promise((resolve) => {
    chrome.runtime.sendMessage({ type: 'OVERHEARD_TRANSLATE_WORD', word, sourceLang, targetLang }, (res) => {
      if (chrome.runtime.lastError) {
        console.warn('[Overheard] Translation message error:', chrome.runtime.lastError.message);
        resolve(null);
        return;
      }
      resolve(res?.success ? res.translation : null);
    });
  });
};

function getCurrentVideoId(): string | null {
  return new URLSearchParams(window.location.search).get('v');
}

const App = () => {
  const [displayPrimary, setDisplayPrimary] = useState('');
  const [speechVolume, setSpeechVolume] = useState(1);
  const [displaySecondary, setDisplaySecondary] = useState('');
  const [isEnabled, setEnabled] = useState(true);
  const [captionStyle, setCaptionStyle] = useState<CaptionStyle>(DEFAULT_CAPTION_STYLE);
  const [fontSize, setFontSize] = useState(DEFAULT_FONT_SIZE);
  const [overlayLayout, setOverlayLayout] = useState<OverlayLayout>(DEFAULT_OVERLAY_LAYOUT);
  const [primaryLangCode, setPrimaryLangCode] = useState('en');
  const [secondaryLangCode, setSecondaryLangCode] = useState('pt-BR');
  const engine = useRef(new SubtitleEngine());
  const lastLoadedVideoId = useRef<string | null>(null);
  const lastLoadedLangs = useRef<string>('');
  const pendingResolve = useRef<((data: string | null) => void) | null>(null);
  const pendingTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingMatcher = useRef<((url: string) => boolean) | null>(null);
  const pendingTracksResolve = useRef<((tracks: LiveTrack[]) => void) | null>(null);
  const handleVolumeChangeRef = useRef<(() => void) | null>(null);
  const isLoadingSubtitles = useRef(false);
  const loadGeneration = useRef(0);
  const navigateDebounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [primaryLoading, setPrimaryLoading] = useState(false);
  const [secondaryLoading, setSecondaryLoading] = useState(false);

  const getLiveTracks = (): Promise<LiveTrack[]> => {
    return new Promise((resolve) => {
      pendingTracksResolve.current = resolve;
      window.postMessage({ type: 'OVERHEARD_GET_TRACKS' }, '*');
      setTimeout(() => {
        if (pendingTracksResolve.current) {
          pendingTracksResolve.current = null;
          resolve([]);
        }
      }, 2000);
    });
  };

  const waitForCapture = (matcher: (url: string) => boolean): Promise<string | null> => {
    return new Promise((resolve) => {
      pendingResolve.current = resolve;
      pendingMatcher.current = matcher;
      pendingTimer.current = setTimeout(() => {
        console.warn('[Overheard] Capture timed out waiting for track');
        pendingResolve.current = null;
        pendingMatcher.current = null;
        resolve(null);
      }, CAPTURE_TIMEOUT_MS);
    });
  };

  const requestTrack = async (sourceLangCode: string, isTranslation: boolean, targetLangCode?: string): Promise<string | null> => {
    const matcher = (url: string) => {
      if (isTranslation && targetLangCode) return url.includes(`tlang=${targetLangCode}`);
      return url.includes(`lang=${sourceLangCode}`) && !url.includes('tlang=');
    };
    const capturePromise = waitForCapture(matcher);
    window.postMessage({ type: 'OVERHEARD_SET_PLAYER_LANG', sourceLangCode, isTranslation, targetLangCode }, '*');
    return capturePromise;
  };

  const requestTrackWithRetry = async (
    sourceLangCode: string,
    isTranslation: boolean,
    targetLangCode: string | undefined,
    maxRetries = 1
  ): Promise<string | null> => {
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      if (attempt > 0) {
        console.warn(`[Overheard] Retry ${attempt} for`, sourceLangCode, isTranslation ? `-> ${targetLangCode}` : '');
        await new Promise(r => setTimeout(r, 500));
      }
      const raw = await requestTrack(sourceLangCode, isTranslation, targetLangCode);
      if (raw) return raw;
    }
    return null;
  };

  const resolveTrackConfig = (tracks: LiveTrack[], targetCode: string, primaryLanguage: string) => {
    const baseCode = targetCode.split('-')[0];
    const direct = tracks.find(t => t.languageCode === targetCode)
      ?? tracks.find(t => t.languageCode.startsWith(baseCode));
    if (direct) return { sourceLangCode: direct.languageCode, isTranslation: false, targetLangCode: undefined as string | undefined };

    const sourceTrack =
      tracks.find(t => t.languageCode.startsWith(primaryLanguage.split('-')[0])) ??
      tracks.find(t => t.languageCode.startsWith('en')) ??
      tracks[0];

    if (!sourceTrack) return null;
    return { sourceLangCode: sourceTrack.languageCode, isTranslation: true, targetLangCode: baseCode };
  };

  const loadSubtitles = async () => {
  if (isLoadingSubtitles.current) {
    console.log('[Overheard] loadSubtitles already in progress — skipping overlapping call');
    return;
  }
  isLoadingSubtitles.current = true;
  const myGeneration = ++loadGeneration.current;

  try {
    const s = await getSettings();
    setEnabled(s.enabled);
    setCaptionStyle(s.captionStyle);
    setFontSize(s.fontSize);
    setOverlayLayout(s.overlayLayout);
    setPrimaryLangCode(s.primaryLanguage);
    setSecondaryLangCode(s.secondaryLanguage);
    if (!s.enabled) return;

    const videoId = getCurrentVideoId();
    const langsKey = `${s.primaryLanguage}|${s.secondaryLanguage}`;
    const alreadyLoaded = videoId && videoId === lastLoadedVideoId.current && langsKey === lastLoadedLangs.current;

    if (alreadyLoaded) {
      console.log('[Overheard] Skipping reload — same video and language pair already loaded');
      return;
    }

    setPrimaryLoading(true);
    setSecondaryLoading(true);

    let tracks = await getLiveTracks();
    if (loadGeneration.current !== myGeneration) return;

    let tracksAttempt = 1;
    while (tracks.length === 0 && tracksAttempt < 3) {
      console.warn(`[Overheard] No tracks on attempt ${tracksAttempt} — retrying`);
      await new Promise(r => setTimeout(r, 1000));
      if (loadGeneration.current !== myGeneration) return;
      tracks = await getLiveTracks();
      tracksAttempt++;
    }

    if (loadGeneration.current !== myGeneration) return;

    if (tracks.length === 0) {
      console.warn('[Overheard] No caption tracks found for this video after retries');
      engine.current.setPrimaryEntries([]);
      engine.current.setSecondaryEntries([]);
      setPrimaryLoading(false);
      setSecondaryLoading(false);
      return;
    }

    const primaryConfig = resolveTrackConfig(tracks, s.primaryLanguage, s.primaryLanguage);
    const secondaryConfig = resolveTrackConfig(tracks, s.secondaryLanguage, s.primaryLanguage);

    if (primaryConfig) {
      const primaryRaw = await requestTrackWithRetry(primaryConfig.sourceLangCode, primaryConfig.isTranslation, primaryConfig.targetLangCode);
      if (loadGeneration.current !== myGeneration) return;
      engine.current.setPrimaryEntries(primaryRaw ? adapter.parse(primaryRaw) : []);
      console.log('[Overheard] Primary captured:', !!primaryRaw);
    } else {
      console.warn('[Overheard] Could not resolve a primary track config');
    }
    setPrimaryLoading(false);

    await new Promise(r => setTimeout(r, 300));
    if (loadGeneration.current !== myGeneration) return;

    if (secondaryConfig) {
      const secondaryRaw = await requestTrackWithRetry(secondaryConfig.sourceLangCode, secondaryConfig.isTranslation, secondaryConfig.targetLangCode);
      if (loadGeneration.current !== myGeneration) return;
      engine.current.setSecondaryEntries(secondaryRaw ? adapter.parse(secondaryRaw) : []);
      console.log('[Overheard] Secondary captured:', !!secondaryRaw);
    } else {
      console.warn('[Overheard] Could not resolve a secondary track config');
    }
    setSecondaryLoading(false);

    lastLoadedVideoId.current = videoId;
    lastLoadedLangs.current = langsKey;
  } finally {
    isLoadingSubtitles.current = false;
  }
};

  const handleLayoutChange = (layout: OverlayLayout) => {
    setOverlayLayout(layout);
    setSettings({ overlayLayout: layout });
  };

  // Translate the clicked word, then log it to history regardless of which
  // line (primary/secondary) it was clicked from — direction is decided by
  // SubtitleOverlay (always toward "the other line's" language).
  const handleWordClick = async (word: string, sourceLang: string, targetLang: string): Promise<string | null> => {
  const translation = await requestTranslation(word, sourceLang, targetLang);
  if (translation) {
    addWordHistoryEntry({ word, translation, sourceLang, targetLang });
  }
  return translation;
  };

  useEffect(() => {
    setNativeCaptionsHidden(isEnabled);
  }, [isEnabled]);

  useEffect(() => {
    let currentVideo: HTMLVideoElement | null = null;
    let handleTimeUpdate: (() => void) | null = null;
    
    const attachToVideo = () => {
      const video = adapter.getVideoElement();
      if (!video || video === currentVideo) return;
      if (currentVideo && handleTimeUpdate) currentVideo.removeEventListener('timeupdate', handleTimeUpdate);
      if (currentVideo && handleVolumeChangeRef.current) currentVideo.removeEventListener('volumechange', handleVolumeChangeRef.current);

      currentVideo = video;
      handleTimeUpdate = () => {
        const { primaryText, secondaryText } = engine.current.getActiveEntries(video.currentTime);
        setDisplayPrimary(primaryText);
        setDisplaySecondary(secondaryText);
      };
      video.addEventListener('timeupdate', handleTimeUpdate);

      const handleVolumeChange = () => {
        setSpeechVolume(video.muted ? 0 : video.volume);
      };
      handleVolumeChangeRef.current = handleVolumeChange;
      video.addEventListener('volumechange', handleVolumeChange);
      handleVolumeChange();
    };

    const handleNavigate = () => {
      const newVideoId = getCurrentVideoId();

      if (navigateDebounceTimer.current) clearTimeout(navigateDebounceTimer.current);

      navigateDebounceTimer.current = setTimeout(() => {
        attachToVideo();

        if (!newVideoId) {
          console.log('[Overheard] yt-navigate-finish fired with no readable video ID yet — ignoring');
          return;
        }

        if (newVideoId === lastLoadedVideoId.current) {
          console.log('[Overheard] yt-navigate-finish fired but video unchanged — skipping reload');
          return;
        }

        console.log('[Overheard] yt-navigate-finish — reloading subtitles for new video');
        engine.current.setPrimaryEntries([]);
        engine.current.setSecondaryEntries([]);
        setDisplayPrimary('');
        setDisplaySecondary('');
        loadSubtitles();
      }, 400);
    };

    const handleMessage = (event: MessageEvent) => {
      if (event.source !== window) return;

      if (event.data.type === 'OVERHEARD_TRACKS' && pendingTracksResolve.current) {
        const resolve = pendingTracksResolve.current;
        pendingTracksResolve.current = null;
        resolve(event.data.tracks ?? []);
        return;
      }

      if (event.data.type === 'OVERHEARD_DATA') {
        const url = event.data.url as string;
        if (pendingResolve.current && pendingMatcher.current) {
          if (pendingMatcher.current(url)) {
            if (pendingTimer.current) clearTimeout(pendingTimer.current);
            const resolve = pendingResolve.current;
            pendingResolve.current = null;
            pendingMatcher.current = null;
            resolve(event.data.data);
          } else {
            console.log('[Overheard] Ignored non-matching timedtext packet:', url);
          }
        }
      }
      if (event.data.type === 'OVERHEARD_TRANSLATION_FAILED') {
        const url = event.data.url as string;
        if (pendingResolve.current && pendingMatcher.current && pendingMatcher.current(url)) {
          if (pendingTimer.current) clearTimeout(pendingTimer.current);
          const resolve = pendingResolve.current;
          pendingResolve.current = null;
          pendingMatcher.current = null;
          console.warn('[Overheard] Translation exhausted internal retries — failing fast instead of waiting for the outer timeout');
          resolve(null);
        }
      }
    };

    const handleStorageChange = (changes: { [key: string]: chrome.storage.StorageChange }) => {
      if (changes.primaryLanguage || changes.secondaryLanguage || changes.enabled) {
        loadSubtitles();
        return;
      }
      if (changes.captionStyle) setCaptionStyle(changes.captionStyle.newValue as CaptionStyle);
      if (changes.fontSize) setFontSize(changes.fontSize.newValue as number);
      if (changes.overlayLayout) setOverlayLayout(changes.overlayLayout.newValue as OverlayLayout);
    };
    
    attachToVideo();
    loadSubtitles();

    window.addEventListener('message', handleMessage);
    window.addEventListener('yt-navigate-finish', handleNavigate);
    chrome.storage.onChanged.addListener(handleStorageChange);
    
    return () => {
      window.removeEventListener('message', handleMessage);
      window.removeEventListener('yt-navigate-finish', handleNavigate);
      chrome.storage.onChanged.removeListener(handleStorageChange);
      if (currentVideo && handleTimeUpdate) currentVideo.removeEventListener('timeupdate', handleTimeUpdate);
    };
    
  }, []);

  if (!isEnabled) return null;
  return (
    <SubtitleOverlay
      primaryText={displayPrimary}
      secondaryText={displaySecondary}
      captionStyle={captionStyle}
      fontSize={fontSize}
      layout={overlayLayout}
      onLayoutChange={handleLayoutChange}
      primaryLanguage={primaryLangCode}
      secondaryLanguage={secondaryLangCode}
      onWordClick={handleWordClick}
      speechVolume={speechVolume}
      primaryLoading={primaryLoading}
      secondaryLoading={secondaryLoading}
    />
  );
};

function getMountTarget(): HTMLElement {
  const fsEl = document.fullscreenElement as HTMLElement | null;
  if (fsEl) return fsEl;
  return (document.getElementById('movie_player') || document.querySelector('.html5-video-player') || document.body) as HTMLElement;
}

function syncContainerToVideo(container: HTMLElement, video: HTMLVideoElement | null) {
  if (!video) return;
  const rect = video.getBoundingClientRect();
  Object.assign(container.style, {
    position: 'fixed',
    left: `${rect.left}px`,
    top: `${rect.top}px`,
    width: `${rect.width}px`,
    height: `${rect.height}px`,
  });
}

function reparentContainer(container: HTMLElement) {
  const target = getMountTarget();
  if (container.parentElement !== target) {
    target.appendChild(container);
  }
}

function injectUI() {
  if (document.getElementById('overheard-root')) return;

  nativeCaptionStyleEl = document.createElement('style');
  nativeCaptionStyleEl.textContent = '.ytp-caption-window-container { display: none !important; }';
  (document.head || document.documentElement).appendChild(nativeCaptionStyleEl);

  if (!document.getElementById('overheard-google-fonts')) {
    const fontLink = document.createElement('link');
    fontLink.id = 'overheard-google-fonts';
    fontLink.rel = 'stylesheet';
    fontLink.href = GOOGLE_FONTS_URL;
    (document.head || document.documentElement).appendChild(fontLink);
  }

  const container = document.createElement('div');
  container.id = 'overheard-root';
  Object.assign(container.style, { zIndex: '2147483647', pointerEvents: 'none' });

  reparentContainer(container);

  let observedVideo: HTMLVideoElement | null = null;
  let videoResizeObserver: ResizeObserver | null = null;

  const attachVideoTracking = () => {
    const video = adapter.getVideoElement();
    if (!video || video === observedVideo) return;
    if (videoResizeObserver) videoResizeObserver.disconnect();

    observedVideo = video;
    syncContainerToVideo(container, video);
    videoResizeObserver = new ResizeObserver(() => syncContainerToVideo(container, observedVideo));
    videoResizeObserver.observe(video);
  };

  attachVideoTracking();

  window.addEventListener('resize', () => syncContainerToVideo(container, observedVideo));
  window.addEventListener('scroll', () => syncContainerToVideo(container, observedVideo), true);

  document.addEventListener('fullscreenchange', () => {
    requestAnimationFrame(() => requestAnimationFrame(() => {
      reparentContainer(container);
      syncContainerToVideo(container, observedVideo);
    }));
  });

  window.addEventListener('yt-navigate-finish', () => {
    reparentContainer(container);
    attachVideoTracking();
  });

  const shadow = container.attachShadow({ mode: 'open' });
  const root = document.createElement('div');
  shadow.appendChild(root);
  createRoot(root).render(<App />);
}
if (document.body) injectUI();
else window.addEventListener('load', injectUI);